# -*- coding: utf-8 -*-
"""areadev

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fv-_9Vr61XV_ieko3cCngH11BAHzW_mQ
"""

import serial
import csv

# Open a serial connection to the Arduino
serial_port = 'COM6'  # Replace with the appropriate serial port
baud_rate = 115200
ser = serial.Serial(serial_port, baud_rate)

# Create and open a CSV file for writing
csv_file = open('sensor_data.csv', 'w', newline='')
csv_writer = csv.writer(csv_file)

# Write the header row to the CSV file
csv_writer.writerow(["AccX", "AccY", "AccZ", "GyroX", "GyroY", "GyroZ"])

try:
    while True:
        # Read a line of data from the Arduino
        data = ser.readline().decode().strip()

        # Split the data into individual values
        values = data.split(",")

        # Extract numeric values (skip labels)
        numeric_values = [float(val.split(":")[1]) for val in values if ":" in val]

        # Ensure that the received data contains the expected number of values
        if len(numeric_values) == 6:
            # Write the data to the CSV file
            csv_writer.writerow(numeric_values)

except KeyboardInterrupt:
    pass

# Close the CSV file and the serial connection
csv_file.close()
ser.close()